#GET
GET http://localhost:8080/api/v1/fotoFesta
Content-Type: application/json
###

GET http://localhost:8080/api/v1/fotoFesta/1/fotofesta
Content-Type: application/json
###




#POST
POST http://localhost:8080/api/v1/fotoFesta
Content-Type: application/json

{
    "url": "a",
    "fkFotoFesta": 2
}
###

#PUT
PUT http://localhost:8080/api/v1/fotoFesta
Content-Type: application/json

{
    "url": "bagunça",
    "idFoto": "1"
}
###

#DELETE
DELETE   http://localhost:8080/api/v1/fotoFesta/2
Content-Type: application/json


###